// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/datasources": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回所有已注册的第三方数据源信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据源"
                ],
                "summary": "列出所有数据源",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/proxy.ClientInfo"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "检查服务是否运行",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "健康检查"
                ],
                "summary": "健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/lvyun/business-report": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取营业日报表数据，包括代码、描述、本日发生、本月发生、本年发生等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "绿云接口"
                ],
                "summary": "营业报表数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "酒店代码",
                        "name": "hotel_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "开始日期 (格式: 2022-10-20 00:00:00)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束日期 (格式: 2022-10-21 00:00:00)",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/lvyun.BusinessReportResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/lvyun/checkouts": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取结账单流水数据，包括结账流水号、账号、入账类型、入账代码、金额等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "绿云接口"
                ],
                "summary": "结账单数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "酒店代码",
                        "name": "hotel_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "营业日期 (格式: 2025-10-20 00:00:00)",
                        "name": "biz_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/lvyun.CheckoutResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/lvyun/health": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "检查绿云接口连接状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "绿云接口"
                ],
                "summary": "绿云接口健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/lvyun/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回绿云接口的基本信息和状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "绿云接口"
                ],
                "summary": "获取绿云接口信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/proxy.ClientInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/lvyun/registrations": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取酒店登记单数据，包括账号、姓名、房型、房号、入住日期、离店日期、主单id等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "绿云接口"
                ],
                "summary": "登记单数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "酒店代码",
                        "name": "hotel_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "开始日期 (格式: 2025-10-20 00:00:00)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束日期 (格式: 2025-10-21 00:00:00)",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/lvyun.RegistrationResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/lvyun/reservations": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取酒店预订数据，包括账号、姓名、房型、房号、入住日期、离店日期等",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "绿云接口"
                ],
                "summary": "预订单数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "酒店代码",
                        "name": "hotel_code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "开始日期 (格式: 2025-10-20 00:00:00)",
                        "name": "start_date",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "结束日期 (格式: 2025-10-21 00:00:00)",
                        "name": "end_date",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/lvyun.ReservationResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/ps/employee-honors": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取PS系统员工荣誉信息，支持分页查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PS接口"
                ],
                "summary": "员工荣誉数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分区字段 (格式: YYYYMMDD，示例: 20251113)",
                        "name": "ds",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页编号 (默认: 1)",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小 (默认: 100，最大: 2000)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "emplid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "是否保存到数据库 (默认: true)",
                        "name": "save_db",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/ps/employees-all": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取PS系统员工全量信息，支持分页查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PS接口"
                ],
                "summary": "员工全量数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分区字段 (格式: YYYYMMDD，示例: 20251113)",
                        "name": "ds",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页编号 (默认: 1)",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小 (默认: 100，最大: 2000)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "emplid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "是否保存到数据库 (默认: true)",
                        "name": "save_db",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/ps/employees-inc": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取PS系统员工增量信息，支持分页查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PS接口"
                ],
                "summary": "员工增量数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分区字段 (格式: YYYYMMDD，示例: 20251113)",
                        "name": "ds",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页编号 (默认: 1)",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小 (默认: 100，最大: 2000)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "emplid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "是否保存到数据库 (默认: true)",
                        "name": "save_db",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/ps/family-main": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取PS系统家族父表信息，支持分页查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PS接口"
                ],
                "summary": "家族父表数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分区字段 (格式: YYYYMMDD，示例: 20251113)",
                        "name": "ds",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页编号 (默认: 1)",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小 (默认: 100，最大: 2000)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "emplid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "是否保存到数据库 (默认: true)",
                        "name": "save_db",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/ps/family-members": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取PS系统家族成员信息，支持分页查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PS接口"
                ],
                "summary": "家族成员数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分区字段 (格式: YYYYMMDD，示例: 20251013)",
                        "name": "ds",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页编号 (默认: 1)",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小 (默认: 100，最大: 2000)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "员工ID",
                        "name": "emplid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "是否保存到数据库 (默认: true)",
                        "name": "save_db",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/ps/health": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "检查PS接口连接状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PS接口"
                ],
                "summary": "PS接口健康检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/ps/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "返回PS接口的基本信息和状态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PS接口"
                ],
                "summary": "获取PS接口信息",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/proxy.ClientInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/ps/organizations-all": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取PS系统组织全量信息，支持分页查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PS接口"
                ],
                "summary": "组织全量数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分区字段 (格式: YYYYMMDD，示例: 20251113)",
                        "name": "ds",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页编号 (默认: 1)",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小 (默认: 100，最大: 2000)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "是否保存到数据库 (默认: true)",
                        "name": "save_db",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/ps/organizations-inc": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取PS系统组织增量信息，支持分页查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PS接口"
                ],
                "summary": "组织增量数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分区字段 (格式: YYYYMMDD，示例: 20251113)",
                        "name": "ds",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页编号 (默认: 1)",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小 (默认: 100，最大: 2000)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "是否保存到数据库 (默认: true)",
                        "name": "save_db",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/ps/positions-all": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取PS系统岗位全量信息，支持分页查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PS接口"
                ],
                "summary": "岗位全量数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分区字段 (格式: YYYYMMDD，示例: 20251113)",
                        "name": "ds",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页编号 (默认: 1)",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小 (默认: 100，最大: 2000)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "是否保存到数据库 (默认: true)",
                        "name": "save_db",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/ps/positions-inc": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取PS系统岗位增量信息，支持分页查询",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PS接口"
                ],
                "summary": "岗位增量数据",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分区字段 (格式: YYYYMMDD，示例: 20251113)",
                        "name": "ds",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "页编号 (默认: 1)",
                        "name": "page_num",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页大小 (默认: 100，最大: 2000)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "是否保存到数据库 (默认: true)",
                        "name": "save_db",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/ps/trigger-sync": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "手动触发PS系统数据同步任务",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PS接口"
                ],
                "summary": "手动触发数据同步",
                "parameters": [
                    {
                        "type": "string",
                        "description": "数据类型 (family-members/all，默认: family-members)",
                        "name": "data_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/controllers.APIResponse"
                        }
                    }
                }
            }
        },
        "/ready": {
            "get": {
                "description": "检查服务是否就绪(验证配置)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "健康检查"
                ],
                "summary": "就绪检查",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/task-records": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询定期任务的执行记录，支持按数据源、任务类型、状态过滤",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据源"
                ],
                "summary": "查询任务执行记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "数据源名称（lvyun/ps）",
                        "name": "data_source",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "任务类型（如：reservations, positions-inc等）",
                        "name": "task_type",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "执行状态（running/success/failed）",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "返回记录数（默认100）",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/proxy.TaskRecord"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/task-statistics": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取任务执行的统计信息（总数、成功数、失败数、运行中）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据源"
                ],
                "summary": "获取任务统计信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "数据源名称（lvyun/ps）",
                        "name": "data_source",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controllers.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": true
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.APIResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "lvyun.BusinessReportResponse": {
            "type": "object",
            "properties": {
                "BizDate": {
                    "description": "日期",
                    "type": "string"
                },
                "Code": {
                    "description": "代码",
                    "type": "string"
                },
                "Day": {
                    "description": "本日发生",
                    "type": "number"
                },
                "DayRebate": {
                    "description": "本日发生-rebate",
                    "type": "number"
                },
                "Descript": {
                    "description": "描述",
                    "type": "string"
                },
                "HotelCode": {
                    "description": "酒店代码",
                    "type": "string"
                },
                "HotelName": {
                    "description": "酒店名称",
                    "type": "string"
                },
                "Month": {
                    "description": "本月发生",
                    "type": "number"
                },
                "MonthRebate": {
                    "description": "本月发生-rebate",
                    "type": "number"
                },
                "Remark": {
                    "description": "备注",
                    "type": "string"
                },
                "TaxDay": {
                    "description": "本日发生-税",
                    "type": "number"
                },
                "TaxMonth": {
                    "description": "本月发生-税",
                    "type": "number"
                },
                "TaxYear": {
                    "description": "本年发生-税",
                    "type": "number"
                },
                "Year": {
                    "description": "本年发生",
                    "type": "number"
                },
                "YearRebate": {
                    "description": "本年发生-rebate",
                    "type": "number"
                }
            }
        },
        "lvyun.CheckoutResponse": {
            "type": "object",
            "properties": {
                "Accnt": {
                    "description": "账号",
                    "type": "string"
                },
                "Amount": {
                    "description": "金额",
                    "type": "number"
                },
                "ArrDep": {
                    "description": "到达日期",
                    "type": "string"
                },
                "Arrange": {
                    "description": "入账类型",
                    "type": "string"
                },
                "BizDate": {
                    "description": "日期",
                    "type": "string"
                },
                "DepDate": {
                    "description": "离开日期",
                    "type": "string"
                },
                "HotelCode": {
                    "description": "酒店代码",
                    "type": "string"
                },
                "HotelName": {
                    "description": "酒店名称",
                    "type": "string"
                },
                "Id": {
                    "description": "绿云系统ID(唯一主键)",
                    "type": "integer"
                },
                "Mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "NAME": {
                    "description": "姓名",
                    "type": "string"
                },
                "Remark": {
                    "description": "备注",
                    "type": "string"
                },
                "Rmno": {
                    "description": "房间号",
                    "type": "string"
                },
                "TaCode": {
                    "description": "入账代码",
                    "type": "string"
                },
                "TaDesc": {
                    "description": "入账描述",
                    "type": "string"
                }
            }
        },
        "lvyun.RegistrationResponse": {
            "type": "object",
            "properties": {
                "Adult": {
                    "description": "成人",
                    "type": "integer"
                },
                "ArrDate": {
                    "description": "入住日期",
                    "type": "string"
                },
                "CreateDatetime": {
                    "description": "预定时间",
                    "type": "string"
                },
                "CreateUser": {
                    "description": "创建用户",
                    "type": "string"
                },
                "DepDate": {
                    "description": "离店日期",
                    "type": "string"
                },
                "HotelCode": {
                    "description": "酒店代码",
                    "type": "string"
                },
                "HotelName": {
                    "description": "酒店名称",
                    "type": "string"
                },
                "Id": {
                    "description": "绿云系统ID(唯一主键)",
                    "type": "integer"
                },
                "MasterId": {
                    "description": "主单id",
                    "type": "string"
                },
                "Mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "Packages": {
                    "description": "包价",
                    "type": "string"
                },
                "Remark": {
                    "description": "备注",
                    "type": "string"
                },
                "RmType": {
                    "description": "房型",
                    "type": "string"
                },
                "Rmno": {
                    "description": "房号",
                    "type": "string"
                },
                "Rmnum": {
                    "description": "房数",
                    "type": "integer"
                },
                "RsvClass": {
                    "description": "客户类型",
                    "type": "string"
                },
                "RsvNo": {
                    "description": "预定单号",
                    "type": "string"
                },
                "Sta": {
                    "description": "订单状态 (I代表入住状态)",
                    "type": "string"
                },
                "name": {
                    "description": "姓名 (注意: API返回的是小写name)",
                    "type": "string"
                }
            }
        },
        "lvyun.ReservationResponse": {
            "type": "object",
            "properties": {
                "Adult": {
                    "description": "成人",
                    "type": "integer"
                },
                "ArrDate": {
                    "description": "入住日期",
                    "type": "string"
                },
                "CreateDatetime": {
                    "description": "预定时间",
                    "type": "string"
                },
                "CreateUser": {
                    "description": "创建用户",
                    "type": "string"
                },
                "DepDate": {
                    "description": "离店日期",
                    "type": "string"
                },
                "HotelCode": {
                    "description": "酒店代码",
                    "type": "string"
                },
                "HotelName": {
                    "description": "酒店名称",
                    "type": "string"
                },
                "Id": {
                    "description": "绿云系统ID(唯一主键)",
                    "type": "integer"
                },
                "Mobile": {
                    "description": "手机号",
                    "type": "string"
                },
                "Name": {
                    "description": "姓名",
                    "type": "string"
                },
                "Packages": {
                    "description": "包价",
                    "type": "string"
                },
                "Remark": {
                    "description": "备注",
                    "type": "string"
                },
                "RmType": {
                    "description": "房型",
                    "type": "string"
                },
                "Rmno": {
                    "description": "房号",
                    "type": "string"
                },
                "Rmnum": {
                    "description": "房数",
                    "type": "integer"
                },
                "RsvClass": {
                    "description": "客户类型",
                    "type": "string"
                },
                "RsvNo": {
                    "description": "预定单号",
                    "type": "string"
                },
                "Sta": {
                    "description": "订单状态 (R代表预定状态)",
                    "type": "string"
                }
            }
        },
        "proxy.ClientInfo": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "route_prefix": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "proxy.TaskRecord": {
            "type": "object",
            "properties": {
                "data_source": {
                    "description": "数据源名称（lvyun/ps）",
                    "type": "string"
                },
                "duration": {
                    "description": "执行时长（毫秒）",
                    "type": "integer"
                },
                "end_time": {
                    "description": "结束时间",
                    "type": "string"
                },
                "error_msg": {
                    "description": "错误信息",
                    "type": "string"
                },
                "id": {
                    "description": "记录ID（使用时间戳生成）",
                    "type": "string"
                },
                "record_count": {
                    "description": "处理记录数",
                    "type": "integer"
                },
                "start_time": {
                    "description": "开始时间",
                    "type": "string"
                },
                "status": {
                    "description": "执行状态",
                    "allOf": [
                        {
                            "$ref": "#/definitions/proxy.TaskStatus"
                        }
                    ]
                },
                "task_type": {
                    "description": "任务类型（reservations/positions-inc等）",
                    "type": "string"
                }
            }
        },
        "proxy.TaskStatus": {
            "type": "string",
            "enum": [
                "running",
                "success",
                "failed"
            ],
            "x-enum-comments": {
                "TaskStatusFailed": "失败",
                "TaskStatusRunning": "执行中",
                "TaskStatusSuccess": "成功"
            },
            "x-enum-descriptions": [
                "执行中",
                "成功",
                "失败"
            ],
            "x-enum-varnames": [
                "TaskStatusRunning",
                "TaskStatusSuccess",
                "TaskStatusFailed"
            ]
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "API Key认证，也可以使用 Authorization: Bearer \u003ckey\u003e",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/swagger/datahub-external",
	Schemes:          []string{},
	Title:            "数据底座外部接口代理服务 API",
	Description:      "代理第三方数据接口，如绿云酒店管理系统等",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
